version: "3.9"

services:
  mysql:
    image: mysql:oracle
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      TZ: "Asia/Tokyo"
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
  
  # web:
  #   container_name: nginx
  #   ports:
  #     - "8000:8000"
  #   build:
  #     dockerfile: ./Nginx/Dockerfile
volumes:
  db-store: